---
name: "build:x40.link"

on:
  push:
    branches: ["main"]

jobs:
  release:
    # The machine type on which the workload is running
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    #
    # These machines come with podman pre-installed
    # See https://github.com/redhat-actions/podman-login?tab=readme-ov-file#podman-login
    runs-on: ubuntu-24.04

    # The environment to which main is deployed
    environment:
      name: x40-link
      url: https://x40.link/

    permissions:
      contents: read

      # Needed to cancel the build
      actions: write

      # Push images to GitHub
      # See https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      packages: write

      # Authenticate via Google Cloud
      # See https://github.com/google-github-actions/auth
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            artifact:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'Containerfile'
              - '.github/workflows/main+x40.link.yml'
              - 'deploy/prod/cr/**'
              - 'etc/**'

      - name: "(Optionally) Cancel the build"
        if: ${{ steps.filter.outputs.artifact == 'false' }}

        # Wait required, as this pauses the build until its cancelled.
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ github.token }}

      # See https://github.com/redhat-actions/podman-login
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}

      # Authenticate to Google Cloud, giving the step an ID and requesting an access token.
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: andrewhowdencom
          workload_identity_provider: projects/422614898574/locations/global/workloadIdentityPools/github--production/providers/github
          service_account: github-actions-at-x40-link@andrewhowdencom.iam.gserviceaccount.com
          token_format: access_token
          # This output is used in the next step.
          access_token_lifetime: '300s'

      # See https://github.com/redhat-actions/podman-login
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: europe-west3-docker.pkg.dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: "Install tools"
        run: task tools/go/install

      - name: Build
        run: task container/all

      - name: Release
        run: task cloudrun/apply
